### ISSUE TITLE
global variables cannot be removed

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#412]
Error message:
11:04:51 WARNING - gui.controllers.global_variable_manager: The respective core element of GlobalVariableManagerController.list_store couldn't be removed. -> 'str' object has no attribute 'parent'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-10-05 09:05:24+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I will look at it. There are a lot of lines from Lukas and it looks like a bad merge because some lines are labeled him and I thought I wrote them and other lines look like kind of  a re-factoring disaster.

Originally created by @Rbelder  at 2017-10-05 13:19:07+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I think the problem is solved by commit  ea1eab6. Respective test of the widget form view site not only by controller calls are needed to avoid this kind of re-factoring error in the future. Please test it and give some feedback.

Originally created by @Rbelder  at 2017-10-05 14:15:01+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
yeas i will test it and make the release afterward, as this is a critical functionality

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-10-05 14:15:45+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Solved thx! 👍 

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-10-05 14:42:54+00:00 (moved from RMC internal repository)
